import Sidebar from '@/components/sidebar/sidebar';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div
      style={{
        display: 'grid',
        gridTemplateColumns: '20% 80%',
        backgroundColor: 'white',
        minHeight: '100vh',
      }}
    >
      <Sidebar />
      <main className={`w-full ${inter.className}`}>{children}</main>
    </div>
  );
}
